# 08 Flask


## Plan for the Lecture

1. a

2. a

3. a

## 1.0 What is Flask?

* Flask is a framework for developing web applications, utilizing HTML and CSS to provide an interface for Python.

* Flask includes a built-in development server, unit testing, and RESTful request handling, a templating engine called Jinja2 for dynamic web pages. 

* Django is a more comprehensive Python web framework, featuring DjangoAdmin, but what you learn in Flask is transferable.

* See the documentation at : http://flask.palletsprojects.com/   


## 1.1 Installing Flask 

`pip install flask`

or 

`python3 -m pip install -U flask --user`

## 1.2 Make folder directory: 

* You could type the following into a terminal
`mkdir my_flask_app` or alternatively create this folder manually in your GUI. 

* Next you want to <b><u>c</b></u>hange <b><u>d</u></b>irectory with `cd`
`cd my_flask_app`

* Now that you are pointing to this root directory, start by creating an `app.py` python file. 

\my_flask_app<br>
&nbsp;&nbsp;&nbsp;&nbsp;`\app.py`


## Your `app.py` file:

* Inside your `app.py` file, copy the below Python script into this file, and then save. 

In [ ]:
from flask import Flask
# First Flask App
app = Flask(__name__)

@app.route('/')
def home():
    return "Hello, Flask!"

if __name__ == '__main__':
    app.run(debug=True)


Check this works by running the following in a terminal: 

`python app.py`

Hopefully, in your web browser, you'll see something like the following (the below is a different example, so the port number will be different, as will the message): 
![hello_f](https://d33wubrfki0l68.cloudfront.net/39e9486b028ee4bc7327d6a2c69e27790f95640f/f69aa/wp-content/uploads/2019/10/flask.png)

If your web browser hasn’t opened automatically, you should be able to click on the localhost link provided, or copy this link into your web browser. By default it is usually: http://127.0.0.1:5000 

## The `templates` folder

* To use HTML in Flask applications, you need to create a ‘template’ folder and place the HTML files in here. 

* This is the same for Django.

Use the terminal command: 
`mkdir templates` 
or alternatively create a new folder manually via your GUI named `templates` within your flask root folder.

\my_flask_app<br>
&nbsp;&nbsp;&nbsp;&nbsp;\templates<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`\home.html`<br>
&nbsp;&nbsp;&nbsp;&nbsp;\app.py

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Hello, Flask with Templates!</h1>
</body>
</html>


which looks like this: 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Hello, Flask with Templates!</h1>
</body>
</html>


## HTML 

* HyperText Markup Language (HTML) was first created in 1991 by Tim-Burners Lee.

* HTML enables developers to define the structure and elements that constitute a page. 

* HTML elements have an opening `< >` tag and closing tag `</ >` 

* HTML 5, first released in 2008, remains the latest version of HTML to date.



## Copy the code below into a `index.html` file

<!DOCTYPE html>
<html>
   <head>
      <title>Page Title</title>
   </head>
   <body>
      <h1>This is a Heading</h1>
      <p>This is a paragraph</p>
   </body>
</html>

Markdown can actually read HTML! See below:

<!DOCTYPE html>
<html>
   <head>
      <title>Page Title</title>
   </head>
   <body>
      <h1>This is a Heading</h1>
      <p>This is a paragraph</p>
   </body>
</html>


## HTML Headings `<h1>` - `<h6>`: 

<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>

## Markdown headings are `#` to `#######`

# Heading 1 
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading 6

## CSS

* Cascading Style Sheets (CSS) was first released in December 1996.

* CSS enables developers to define the presentation of HTML elements – known as rules

* CSS rules are specified using `{` and `}` with values being assigned by the `=` operator and `;` 

* CSS 3, first released in 1999, and had over 40 modules by 2011. It is the latest major version of CSS to date.


## Copy the code below into a `style.css` file

h1 {
    color: #243bb9;
}
p {
    color:#9e3992;
}


#### 1. Import NumPy as np

#### 2. Create an array of 10 zeros 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 3. Create an array of 10 ones

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### 4. Create an array of 10 fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### 5. Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Create a 3x3 identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 9. Use NumPy to generate a random number between 0 and 1

array([ 0.42829726])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### 11. Create the following matrix:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code to produce the following output (from referrring to mat): 

``` 
array([[12, 13, 14, 15],  
       [17, 18, 19, 20],  
       [22, 23, 24, 25]])
```

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code below to produce the following output (from referring to mat): 
``` 20 ```

20

#### 15. Write code below to produce the following output (from referring to mat):
  
```
array([[ 2],
       [ 7],
       [12]])
```

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that produces the following output (from referring to mat)

``` array([21, 22, 23, 24, 25])```

array([21, 22, 23, 24, 25])

#### 17. Write code that produces the following output (from referring to mat)

```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### 18. Get the sum of all the values in mat

325

#### 19. Get the standard deviation of the values in mat

7.2111025509279782

#### 20. Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])